services:
  db:
    image: mariadb
    hostname: dbhost
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: linuxtips
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - ./data/mariadb-volume:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mariadb-admin" ,"ping", "-h", "localhost", "-u", "root", "-p123456"]
      timeout: 20s
      retries: 10